EDA Using Python Pandas

In [123]:
import pandas as pd
print(pd.__version__)

3.0.5

In [124]:
listings = pd.read_json("../data/listings_final_expanded.json")
listings.head()

,Listing_ID,City,Property_Type,Price,Sqft,Date_Listed,Agent_ID,Latitude,Longitude
0,L00001,New York,Apartment,1.655144e+06,2753.009121,2023-05-06,A0015,33.965208,-69.861589
1,L00002,Los Angeles,Apartment,1.519141e+06,4966.988193,2023-02-14,A0038,42.547892,-90.277860
2,L00003,Houston,Apartment,1.624890e+05,1267.003959,2023-04-22,A0015,28.732327,-115.952982
3,L00004,Phoenix,Apartment,1.277016e+06,2128.014429,2024-01-02,A0042,26.403938,-74.771490
4,L00005,Phoenix,Townhouse,5.622970e+05,4178.997421,2023-10-29,A0018,39.425252,-83.917878

In [125]:
listings.shape

(21200, 9)

In [126]:
listings.columns

Index(['Listing_ID', 'City', 'Property_Type', 'Price', 'Sqft', 'Date_Listed',
       'Agent_ID', 'Latitude', 'Longitude'],
      dtype='str')

In [127]:
listings.info()

<class 'pandas.DataFrame'>
RangeIndex: 21200 entries, 0 to 21199
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Listing_ID     21200 non-null  str
 1   City           21200 non-null  str
 2   Property_Type  21200 non-null  str
 3   Price          21200 non-null  float64
 4   Sqft           21200 non-null  float64
 5   Date_Listed    21200 non-null  str
 6   Agent_ID       21200 non-null  str
 7   Latitude       21200 non-null  float64
 8   Longitude      21200 non-null  float64
dtypes: float64(4), str(5)
memory usage: 1.5 MB

In [128]:
listings.describe()

              Price          Sqft      Latitude     Longitude
count  2.120000e+04  21200.000000  21200.000000  21200.000000
mean   2.452708e+06   5113.376093     37.005657    -96.103864
std    1.419864e+06   2737.677578      6.934291     16.729760
min    1.000271e+05    500.005586     25.005494   -124.999086
25%    1.216681e+06   2768.277500     30.972635   -110.672440
50%    2.383803e+06   4974.845000     37.055855    -96.159857
75%    3.679127e+06   7488.895000     42.953084    -81.725564
max    4.999864e+06   9999.590000     48.998007    -67.003724

In [129]:
property_attributes = pd.read_json("../data/property_attributes_final_expanded.json")
property_attributes.head()

,attribute_id,listing_id,bedrooms,bathrooms,floor_number,total_floors,year_built,is_rented,tenant_count,furnishing_status,metro_distance_km,parking_available,power_backup
0,1,L00001,5,3,9,9,2001,True,4,Furnished,7.26,False,True
1,2,L00002,2,2,19,29,2020,False,0,Unfurnished,4.84,True,False
2,3,L00003,2,3,8,26,2007,True,4,Semi-Furnished,4.92,False,False
3,4,L00004,3,3,25,10,2003,False,3,Furnished,1.20,False,True
4,5,L00005,2,2,15,16,2008,True,1,Semi-Furnished,7.90,False,False

In [130]:
agents = pd.read_json("../data/agents_cleaned.json")
agents.head()

,Agent_ID,Name,Phone,Email,commission_rate,deals_closed,rating,experience_years,avg_closing_days
0,A0001,Agent A0001,+1-534-665-8373,a0001@realestate.com,2.00,52,4.3,10,64
1,A0002,Agent A0002,+1-493-463-4698,a0002@realestate.com,2.20,26,3.8,20,82
2,A0003,Agent A0003,+1-290-534-1121,a0003@realestate.com,2.85,297,3.6,21,83
3,A0004,Agent A0004,+1-691-610-4878,a0004@realestate.com,1.67,31,4.5,5,61
4,A0005,Agent A0005,+1-829-613-5411,a0005@realestate.com,1.11,198,4.3,16,67

In [131]:
buyers = pd.read_json("../data/buyers_cleaned.json")
buyers.head()

,buyer_id,sale_id,buyer_type,payment_mode,loan_taken,loan_provider,loan_amount
0,1,L01179,End User,Cash,False,NaN,0
1,2,L00866,Investor,Cheque,False,NaN,0
2,3,L00102,Investor,Cheque,True,Axis,2317757
3,4,L00440,Investor,Bank Transfer,False,NaN,0
4,5,L00059,Investor,UPI,True,HDFC,4191221

In [132]:
sales = pd.read_csv("../data/sales_cleaned.csv")
sales.head()

  Listing_ID    Sale_Price   Date_Sold  Days_on_Market
0     L01179  9.255800e+05  2023-07-07       65.005560
1     L00866  1.054160e+05  2023-06-14       38.004620
2     L00102  1.825184e+06  2023-09-09       22.992622
3     L00440  1.932085e+06  2023-10-29       72.012274
4     L00059  7.765860e+05  2023-05-01      116.000152

In [133]:
listings.shape

(21200, 9)

In [134]:

listings.info()

<class 'pandas.DataFrame'>
RangeIndex: 21200 entries, 0 to 21199
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Listing_ID     21200 non-null  str
 1   City           21200 non-null  str
 2   Property_Type  21200 non-null  str
 3   Price          21200 non-null  float64
 4   Sqft           21200 non-null  float64
 5   Date_Listed    21200 non-null  str
 6   Agent_ID       21200 non-null  str
 7   Latitude       21200 non-null  float64
 8   Longitude      21200 non-null  float64
dtypes: float64(4), str(5)
memory usage: 1.5 MB

In [135]:

property_attributes.info()

<class 'pandas.DataFrame'>
RangeIndex: 21200 entries, 0 to 21199
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   attribute_id       21200 non-null  int64
 1   listing_id         21200 non-null  str
 2   bedrooms           21200 non-null  int64
 3   bathrooms          21200 non-null  int64
 4   floor_number       21200 non-null  int64
 5   total_floors       21200 non-null  int64
 6   year_built         21200 non-null  int64
 7   is_rented          21200 non-null  bool
 8   tenant_count       21200 non-null  int64
 9   furnishing_status  21200 non-null  str
 10  metro_distance_km  21200 non-null  float64
 11  parking_available  21200 non-null  bool
 12  power_backup       21200 non-null  bool
dtypes: bool(3), float64(1), int64(7), str(2)
memory usage: 1.7 MB

In [136]:

agents.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Agent_ID          50 non-null     str
 1   Name              50 non-null     str
 2   Phone             50 non-null     str
 3   Email             50 non-null     str
 4   commission_rate   50 non-null     float64
 5   deals_closed      50 non-null     int64
 6   rating            50 non-null     float64
 7   experience_years  50 non-null     int64
 8   avg_closing_days  50 non-null     int64
dtypes: float64(2), int64(3), str(4)
memory usage: 3.6 KB

In [137]:
buyers.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   buyer_id       20000 non-null  int64
 1   sale_id        20000 non-null  str
 2   buyer_type     20000 non-null  str
 3   payment_mode   20000 non-null  str
 4   loan_taken     20000 non-null  bool
 5   loan_provider  10034 non-null  str
 6   loan_amount    20000 non-null  int64
dtypes: bool(1), int64(2), str(4)
memory usage: 957.2 KB

In [138]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Listing_ID      720 non-null    str
 1   Sale_Price      720 non-null    float64
 2   Date_Sold       720 non-null    str
 3   Days_on_Market  720 non-null    float64
dtypes: float64(2), str(2)
memory usage: 22.6 KB

In [139]:
listings.isnull().sum()

Listing_ID       0
City             0
Property_Type    0
Price            0
Sqft             0
Date_Listed      0
Agent_ID         0
Latitude         0
Longitude        0
dtype: int64

In [140]:
property_attributes.isnull().sum()

attribute_id         0
listing_id           0
bedrooms             0
bathrooms            0
floor_number         0
total_floors         0
year_built           0
is_rented            0
tenant_count         0
furnishing_status    0
metro_distance_km    0
parking_available    0
power_backup         0
dtype: int64

In [141]:
agents.isnull().sum()

Agent_ID            0
Name                0
Phone               0
Email               0
commission_rate     0
deals_closed        0
rating              0
experience_years    0
avg_closing_days    0
dtype: int64

In [142]:
buyers.isnull().sum()

buyer_id            0
sale_id             0
buyer_type          0
payment_mode        0
loan_taken          0
loan_provider    9966
loan_amount         0
dtype: int64

In [143]:
sales.isnull().sum()

Listing_ID        0
Sale_Price        0
Date_Sold         0
Days_on_Market    0
dtype: int64

MySQL Connection

In [144]:
import mysql.connector as mysql
conn = mysql.connect(
    host="localhost",
    user="root",
    password="sha10",
)
cursor = conn.cursor()

In [145]:
cursor.execute("CREATE DATABASE IF NOT EXISTS BrickView")

In [146]:
cursor.execute("Use BrickView")
print("Using BrickView database")

Using BrickView database

In [147]:
create_listings_table_query = """
create table if not exists listings (
    Listing_id varchar(20) primary key,
    City varchar(100),
    Property_type varchar(50),
    Price float,
    Sqft float,
    Date_listed date,
    Agent_ID varchar(20),
    Latitude float,
    Longitude float

);
"""
cursor.execute(create_listings_table_query)
conn.commit()
print("Listings table created successfully!")

Listings table created successfully!

In [148]:
create_property_table_query = """
create table if not exists property_attributes (
    attribute_id INT PRIMARY KEY,
    listing_id VARCHAR(20) NOT NULL,
    bedrooms INT NOT NULL,
    bathrooms INT NOT NULL,
    floor_number INT NOT NULL,
    total_floors INT NOT NULL,
    year_built INT NOT NULL,
    is_rented BOOLEAN NOT NULL,
    tenant_count INT NOT NULL,
    furnishing_status VARCHAR(30) NOT NULL,
    metro_distance_km FLOAT NOT NULL,
    parking_available BOOLEAN NOT NULL,
    power_backup BOOLEAN NOT NULL,

    CONSTRAINT fk_listing
        FOREIGN KEY (listing_id)
        REFERENCES listings(Listing_ID)
);
"""

cursor.execute(create_property_table_query)
conn.commit()

print("Property Attributes table created successfully!")

Property Attributes table created successfully!

In [149]:
create_agents_table_query = """
CREATE TABLE IF NOT EXISTS agents (
    Agent_ID VARCHAR(20) PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Phone VARCHAR(20) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    commission_rate float NOT NULL,
    deals_closed INT NOT NULL,
    rating float NOT NULL,
    experience_years INT NOT NULL,
    avg_closing_days INT NOT NULL
);
"""

cursor.execute(create_agents_table_query)
conn.commit()

print("Agents table created successfully!")

Agents table created successfully!

In [150]:
create_sales_table_query = """
create table if not exists sales (
    sale_id varchar(20) primary key,
    listing_id varchar(20) not null,
    sale_price float not null,
    date_sold date not null,
    days_on_market float not null,

    constraint fk_sales_listing
        foreign key (listing_id)
        references listings(listing_id)
);
"""
cursor.execute(create_sales_table_query)
conn.commit()
print("Sales table created successfully!")

Sales table created successfully!

In [151]:
create_buyers_table_query = """
create table if not exists buyers (
    buyer_id int primary key,
    sale_id varchar(20) not null,
    buyer_type varchar(50) not null,
    payment_mode varchar(30) not null,
    loan_taken boolean not null,
    loan_provider varchar(100),
    loan_amount int not null,
    constraint fk_buyers_sale
        foreign key (sale_id)
        references sales(sale_id)
);
"""
cursor.execute(create_buyers_table_query)
conn.commit()
print("Buyers table created successfully!")

Buyers table created successfully!

Insert into table

In [152]:
for _, row in agents.iterrows():
    cursor.execute("""
        INSERT INTO agents (Agent_ID, Name, Phone, Email, commission_rate, deals_closed, rating, experience_years, avg_closing_days)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
    """, tuple(row))
conn.commit()
print("Agents data inserted successfully!")

Agents data inserted successfully!

In [153]:
for _, row in listings.iterrows():
    cursor.execute("""
        INSERT INTO listings (Listing_id, City, Property_type, Price, Sqft, Date_listed, Agent_ID, Latitude, Longitude)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
    """, tuple(row))
conn.commit()
print("Listings data inserted successfully!")

Listings data inserted successfully!

In [154]:
for _, row in property_attributes.iterrows():
    cursor.execute("""
        INSERT INTO property_attributes (attribute_id, listing_id, bedrooms, bathrooms, floor_number, total_floors, year_built, is_rented, tenant_count, furnishing_status, metro_distance_km, parking_available, power_backup)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    """, tuple(row))
conn.commit()
print("Property attributes data inserted successfully!")

Property attributes data inserted successfully!

In [155]:
for _, row in sales.iterrows():
    cursor.execute("""
        insert into sales (
            sale_id,
            listing_id,
            sale_price,
            date_sold,
            days_on_market
        )
        values (%s, %s, %s, %s, %s)
    """, (
        row["Listing_ID"],   # sale_id
        row["Listing_ID"],   # listing_id
        row["Sale_Price"],
        row["Date_Sold"],
        row["Days_on_Market"]
    ))
conn.commit()
print("Sales data inserted successfully!")

Sales data inserted successfully!

In [156]:
for _, row in buyers.iterrows():
    cursor.execute("""
        INSERT INTO buyers (
            buyer_id,
            sale_id,
            buyer_type,
            payment_mode,
            loan_taken,
            loan_provider,
            loan_amount
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s)
    """, (
        row["buyer_id"],
        row["sale_id"],
        row["buyer_type"],
        row["payment_mode"],
        row["loan_taken"],
        None if pd.isna(row["loan_provider"]) else row["loan_provider"],
        row["loan_amount"]
    ))
conn.commit()
print("Buyers data inserted successfully!")

Buyers data inserted successfully!

Creating Index

In [157]:
cursor.execute("create index idx_city on listings(City);")
cursor.execute("create index idx_agent on listings(Agent_ID);")
cursor.execute("create index idx_property_type on listings(Property_Type);")
cursor.execute("create index idx_sales_listing on sales(Listing_ID);")
conn.commit()
print("Indexes created successfully!")

Indexes created successfully!

In [158]:
cursor.execute("show indexes from listings;")
indexes = cursor.fetchall()
for i in indexes:
    print(i)

('listings', 0, 'PRIMARY', 1, 'Listing_id', 'A', 20884, None, None, '', 'BTREE', '', '', 'YES', None)
('listings', 1, 'idx_city', 1, 'City', 'A', 5, None, None, 'YES', 'BTREE', '', '', 'YES', None)
('listings', 1, 'idx_agent', 1, 'Agent_ID', 'A', 50, None, None, 'YES', 'BTREE', '', '', 'YES', None)
('listings', 1, 'idx_property_type', 1, 'Property_type', 'A', 4, None, None, 'YES', 'BTREE', '', '', 'YES', None)

Creating View

In [159]:
cursor.execute("""
create view city_price as
select City, avg(Price) as average_price, count(*) as total_listings
from listings
group by City;
""")
conn.commit()
print("View 'city_price' created successfully!")

View 'city_price' created successfully!

In [160]:
cursor.execute("""
create view angent_performance as
select a.Agent_ID, a.Name, count(l.Listing_ID) as total_listings,avg(l.Price) as average_price
from agents a join listings l on a.Agent_ID = l.Agent_ID
group by a.Agent_ID, a.Name;
""")
conn.commit()
print("View 'agent_performance' created successfully!")

View 'agent_performance' created successfully!

In [161]:
cursor.execute("""
create view prperty_details as
select l.Listing_ID, l.City, l.Property_Type, l.Price, p.bedrooms, p.bathrooms, p.furnishing_status, p.parking_available from listings l join property_attributes p on l.Listing_ID = p.listing_id;
""")
conn.commit()
print("View 'property_details' created successfully!")

View 'property_details' created successfully!

In [162]:
cursor.execute("""
create view sales_analysis as
select listing_ID,Sale_Price,Date_Sold,Days_on_Market from sales;
""")
conn.commit()
print("View 'sales_analysis' created successfully!")

View 'sales_analysis' created successfully!

 SQL Questions & Queries

    Property & Pricing Analysis

In [163]:
#1
query = """
select city, round(avg(Price), 2) as average_price from listings group by city;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\434035172.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

          city  average_price
0      Chicago     2430677.91
1      Houston     2436811.01
2  Los Angeles     2442418.31
3     New York     2493319.74
4      Phoenix     2459961.76

In [164]:
#2
query = """
select property_type,round(avg(price/sqft), 2) as price_per_sqft from listings group by property_type;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\2076028134.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

  property_type  price_per_sqft
0     Apartment          792.20
1         Condo          754.68
2         House          796.04
3     Townhouse          789.75

In [165]:
#3
query = """
select furnishing_status, round(avg(price), 2) as average_price from property_attributes pa join listings l on pa.listing_id = l.listing_id group by pa.furnishing_status order by average_price asc;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\2381931515.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

  furnishing_status  average_price
0       Unfurnished     2433975.10
1    Semi-Furnished     2461192.65
2         Furnished     2463539.06

In [166]:
#4
query = """
select round(metro_distance_km,0) as Distance_km, round(avg(price),2) as avg_price from property_attributes pa join listings l on pa.listing_ID = l.listing_id group by distance_km order by distance_km;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\436520520.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

    Distance_km   avg_price
0           0.0  2424531.91
1           1.0  2348674.68
2           2.0  2392264.60
3           3.0  2443116.90
4           4.0  2372976.02
5           5.0  2414561.95
6           6.0  2364296.72
7           7.0  2381496.74
8           8.0  2495725.14
9           9.0  2561501.00
10         10.0  2434805.09
11         11.0  2472771.27
12         12.0  2572384.69
13         13.0  2555494.69
14         14.0  2558490.40
15         15.0  2535556.10

In [167]:
#5
query = """
select case when is_rented = 1 then "Rented" else "Non-Rented" end as rental_status, round(avg(price),2) as average_price from property_attributes pa join listings l on pa.listing_ID = l.listing_id group by is_rented;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\2838301730.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

  rental_status  average_price
0        Rented     2457184.91
1    Non-Rented     2448250.30

In [168]:
#6
query = """
select bedrooms, bathrooms, round(avg(price),2) as average_price from property_attributes pa join listings l on pa.listing_ID = l.listing_id group by bedrooms, bathrooms order by bedrooms, bathrooms;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\4258276259.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

    bedrooms  bathrooms  average_price
0          1          1     2434001.41
1          1          2     2509474.77
2          1          3     2459032.59
3          1          4     2455532.96
4          2          1     2455735.36
5          2          2     2378687.66
6          2          3     2482618.93
7          2          4     2555766.23
8          3          1     2426007.98
9          3          2     2409122.73
10         3          3     2455024.25
11         3          4     2478881.22
12         4          1     2434956.39
13         4          2     2450749.99
14         4          3     2393515.03
15         4          4     2471535.91
16         5          1     2384940.46
17         5          2     2478068.17
18         5          3     2424066.83
19         5          4     2527191.97

In [169]:
#7
query = """
select 
case when parking_available = 1 then "Available" else "Not Available" end as parking_status,
case when power_backup = 1 then "Available" else "Not Available" end as power_backup_status,
round(avg(price),2) as average_price 
from property_attributes pa join listings l on pa.listing_ID = l.listing_id 
group by parking_available, power_backup 
order by parking_available, power_backup;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\1633320651.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

  parking_status power_backup_status  average_price
0  Not Available       Not Available     2436677.75
1  Not Available           Available     2446292.59
2      Available       Not Available     2462363.80
3      Available           Available     2465651.62

In [170]:
#8
query = """
select year_built, round(avg(price),2) as average_price from property_attributes pa join listings l on pa.listing_ID = l.listing_id group by year_built order by year_built;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\3662691184.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

    year_built  average_price
0         1990     2533791.60
1         1991     2573916.58
2         1992     2594651.57
3         1993     2611748.25
4         1994     2571504.92
5         1995     2434727.71
6         1996     2391385.74
7         1997     2493105.20
8         1998     2398158.87
9         1999     2498402.47
10        2000     2436148.36
11        2001     2438764.29
12        2002     2433615.48
13        2003     2395754.94
14        2004     2410642.66
15        2005     2518303.24
16        2006     2464741.47
17        2007     2379428.80
18        2008     2471225.25
19        2009     2401619.13
20        2010     2401119.97
21        2011     2440249.43
22        2012     2302495.50
23        2013     2348081.45
24        2014     2358476.99
25        2015     2457272.08
26        2016     2428168.80
27        2017     2393633.46
28        2018     2385864.56
29        2019     2561310.32
30        2020     2465414.50
31        2021     2545272.16
32        2022     2397386.66
33        2023     2500120.41

In [171]:
#9
query = """
select city, round(avg(price),2) as average_price from listings group by city order by average_price desc;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\4289759539.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

          city  average_price
0     New York     2493319.74
1      Phoenix     2459961.76
2  Los Angeles     2442418.31
3      Houston     2436811.01
4      Chicago     2430677.91

In [172]:
#10
query = """
select price_bucket, min(price) as min_price, max(price) as max_price,count(*) as property_count,round(avg(price), 2) as average_price
from (select price, ntile(5) over (order by price) as price_bucket from listings) as t group by price_bucket order by price_bucket;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\177930119.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

   price_bucket  min_price  max_price  property_count  average_price
0             1   100027.0   993974.0            4240      550300.37
1             2   994027.0  1873650.0            4240     1435344.38
2             3  1873920.0  2911780.0            4240     2383955.14
3             4  2911960.0  3944640.0            4240     3421259.24
4             5  3945260.0  4999860.0            4240     4472682.53

    Sales & Market Performance

In [173]:
#11
query = """
select city, round(avg(Days_on_Market), 2) as average_days_on_market from sales s join listings l on s.listing_ID = l.listing_id group by city order by average_days_on_market;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\2932520481.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

          city  average_days_on_market
0      Houston                   58.51
1      Phoenix                   59.65
2     New York                   60.85
3      Chicago                   64.25
4  Los Angeles                   65.13

In [174]:
#12
query = """
select property_type, round(avg(Days_on_Market), 2) as Time_to_Sell from listings l join sales s on l.listing_id = s.listing_id group by property_type order by Time_to_Sell;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\612061037.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

  property_type  Time_to_Sell
0         House         58.34
1     Apartment         60.65
2     Townhouse         60.96
3         Condo         66.54

In [175]:
#13
query = """
select round(sum(case when sale_price > price then 1 else 0 end)*100.0/count(*), 2) as percentage_of_properties_above_listing_price from sales s join listings l on s.listing_id = l.listing_id;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\3720094265.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

   percentage_of_properties_above_listing_price
0                                         49.31

In [176]:
#14
query = """
select city, round(avg(sale_price), 2)/round(avg(price), 2) as sale_to_listing_price_ratio from sales s join listings l on s.listing_id = l.listing_id group by city order by sale_to_listing_price_ratio desc;
""" 
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\3148128402.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

          city  sale_to_listing_price_ratio
0      Chicago                     1.000395
1      Houston                     1.000270
2      Phoenix                     0.998462
3     New York                     0.998116
4  Los Angeles                     0.998087

In [177]:
#15
query="""
select listing_id, days_on_market from sales where days_on_market > 90 order by days_on_market desc;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\3612121679.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

    listing_id  days_on_market
0       L00157        120.0180
1       L00179        120.0110
2       L00259        120.0110
3       L00067        119.9930
4       L00287        119.9700
..         ...             ...
185     L00452         90.9961
186     L00045         90.9924
187     L00812         90.9901
188     L00568         90.0063
189     L00992         90.0035

[190 rows x 2 columns]

In [178]:
#16
query="""
select metro_distance_km, round(avg(days_on_market), 2) as average_days_on_market from property_attributes pa join sales s on pa.listing_id = s.listing_id group by metro_distance_km order by metro_distance_km;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\864439474.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

     metro_distance_km  average_days_on_market
0                 0.21                  108.00
1                 0.22                   81.01
2                 0.24                   21.99
3                 0.25                   58.00
4                 0.26                   99.01
..                 ...                     ...
458               7.93                  102.01
459               7.94                   82.00
460               7.95                   71.67
461               7.99                   65.00
462               8.00                   70.34

[463 rows x 2 columns]

In [179]:
#17
query="""
select monthname(date_sold) as sale_month, count(*) as total_sales from sales group by sale_month order by sale_month;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\1946127662.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

   sale_month  total_sales
0       April           65
1      August           63
2    December           42
3    February           61
4     January           51
5        July           72
6        June           60
7       March           59
8         May           90
9    November           46
10    October           64
11  September           47

In [180]:
#18
query="""
select l.listing_id, l.city, l.property_type, l.price from listings l left join sales s on l.listing_id = s.listing_id where s.listing_id is null;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\4067515331.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

      listing_id         city property_type      price
0         L00002  Los Angeles     Apartment  1519140.0
1         L00005      Phoenix     Townhouse   562297.0
2         L00009     New York     Townhouse  1224550.0
3         L00014      Chicago     Apartment  1377440.0
4         L00015  Los Angeles         House  1069430.0
...          ...          ...           ...        ...
20475     L21196      Phoenix         House   709355.0
20476     L21197      Phoenix         Condo  3288420.0
20477     L21198  Los Angeles     Apartment  1667440.0
20478     L21199  Los Angeles     Townhouse  1648410.0
20479     L21200     New York     Apartment  4991530.0

[20480 rows x 4 columns]

    Agent Performance

In [181]:
#19
query="""
select a.name, count(s.sale_id) as total_sales from agents a join listings l on a.agent_id = l.agent_id join sales s on l.listing_id = s.listing_id group by a.name order by total_sales desc limit 1;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\285797832.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

          name  total_sales
0  Agent A0042           25

In [182]:
#20
query="""
select a.name, round(sum(s.sale_price), 2) as total_sales_revenue from agents a join listings l on a.agent_id = l.agent_id join sales s on l.listing_id = s.listing_id group by a.name order by total_sales_revenue desc limit 3;
"""
result =  pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\197770264.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result =  pd.read_sql(query, conn)

          name  total_sales_revenue
0  Agent A0011           27882272.0
1  Agent A0042           27191606.0
2  Agent A0043           24102418.0

In [187]:
#21
query="""
select name, avg_closing_days from agents order by avg_closing_days asc limit 3;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\3603286236.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

          name  avg_closing_days
0  Agent A0048                15
1  Agent A0035                20
2  Agent A0042                21

In [186]:
#22
query="""
select name,experience_years,deals_closed from agents order by experience_years;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\2876354631.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

           name  experience_years  deals_closed
0   Agent A0035                 1           262
1   Agent A0015                 2            50
2   Agent A0033                 3            14
3   Agent A0007                 4           127
4   Agent A0040                 4           153
5   Agent A0027                 5           157
6   Agent A0004                 5            31
7   Agent A0041                 5            77
8   Agent A0006                 7            63
9   Agent A0034                 7            83
10  Agent A0024                 9           283
11  Agent A0046                10           135
12  Agent A0001                10            52
13  Agent A0050                11           109
14  Agent A0038                12           257
15  Agent A0042                13           231
16  Agent A0030                13           296
17  Agent A0022                13            56
18  Agent A0013                14            11
19  Agent A0025                14           188
20  Agent A0049                14            17
21  Agent A0037                15            16
22  Agent A0016                15           230
23  Agent A0005                16           198
24  Agent A0012                16            24
25  Agent A0029                16            65
26  Agent A0047                16            91
27  Agent A0010                17           292
28  Agent A0026                17           225
29  Agent A0023                18            30
30  Agent A0008                18            74
31  Agent A0009                18           218
32  Agent A0028                19            69
33  Agent A0017                19           156
34  Agent A0043                20            85
35  Agent A0020                20           166
36  Agent A0031                20           226
37  Agent A0002                20            26
38  Agent A0018                20            89
39  Agent A0044                20           236
40  Agent A0032                21           151
41  Agent A0003                21           297
42  Agent A0021                21           233
43  Agent A0048                21           266
44  Agent A0039                21           142
45  Agent A0036                22            98
46  Agent A0014                23            60
47  Agent A0011                23           270
48  Agent A0045                25            99
49  Agent A0019                25            48

In [188]:
#23
query="""
select name,rating, avg_closing_days from agents order by rating desc, avg_closing_days asc;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\2641513534.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

           name  rating  avg_closing_days
0   Agent A0026     5.0                42
1   Agent A0020     5.0                65
2   Agent A0006     4.9                49
3   Agent A0011     4.9                60
4   Agent A0016     4.8                31
5   Agent A0040     4.8                52
6   Agent A0029     4.8                56
7   Agent A0013     4.8                65
8   Agent A0027     4.6                36
9   Agent A0004     4.5                61
10  Agent A0009     4.4                38
11  Agent A0042     4.3                21
12  Agent A0017     4.3                58
13  Agent A0001     4.3                64
14  Agent A0005     4.3                67
15  Agent A0038     4.3                84
16  Agent A0045     4.2                26
17  Agent A0023     4.1                23
18  Agent A0049     4.1                33
19  Agent A0018     4.1                39
20  Agent A0037     4.1                77
21  Agent A0024     4.1                79
22  Agent A0015     4.1                84
23  Agent A0048     4.0                15
24  Agent A0028     4.0                33
25  Agent A0047     4.0                33
26  Agent A0007     3.8                68
27  Agent A0002     3.8                82
28  Agent A0036     3.7                69
29  Agent A0014     3.7                85
30  Agent A0041     3.6                27
31  Agent A0044     3.6                35
32  Agent A0031     3.6                60
33  Agent A0021     3.6                77
34  Agent A0003     3.6                83
35  Agent A0050     3.5                68
36  Agent A0039     3.5                76
37  Agent A0012     3.5                82
38  Agent A0035     3.4                20
39  Agent A0008     3.4                72
40  Agent A0010     3.4                90
41  Agent A0032     3.3                33
42  Agent A0030     3.3                77
43  Agent A0022     3.2                44
44  Agent A0025     3.2                48
45  Agent A0046     3.2                58
46  Agent A0043     3.2                89
47  Agent A0034     3.1                31
48  Agent A0033     3.1                57
49  Agent A0019     3.1                62

In [189]:
#24
query="""
select a.name, round(avg(s.sale_price*a.commission_rate), 2) as avg_commission_earned from agents a join listings l on a.agent_id = l.agent_id join sales s on l.listing_id = s.listing_id group by a.agent_id, a.name order by avg_commission_earned desc;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\35742453.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

           name  avg_commission_earned
0   Agent A0009             3399760.69
1   Agent A0002             3232615.72
2   Agent A0035             3203248.89
3   Agent A0012             3173760.57
4   Agent A0030             3166509.19
5   Agent A0018             3143836.59
6   Agent A0031             3035805.03
7   Agent A0050             2856440.11
8   Agent A0017             2840674.51
9   Agent A0024             2780589.56
10  Agent A0003             2776069.84
11  Agent A0019             2755630.16
12  Agent A0032             2737903.16
13  Agent A0029             2665940.06
14  Agent A0021             2657463.60
15  Agent A0020             2564669.37
16  Agent A0034             2464004.22
17  Agent A0042             2436367.91
18  Agent A0001             2423189.33
19  Agent A0049             2372340.72
20  Agent A0011             2335140.27
21  Agent A0013             2317666.76
22  Agent A0023             2304992.64
23  Agent A0045             2272898.47
24  Agent A0033             2272343.79
25  Agent A0027             2250634.30
26  Agent A0025             2225021.63
27  Agent A0028             2212175.48
28  Agent A0043             2108961.58
29  Agent A0036             2077031.97
30  Agent A0014             2066999.83
31  Agent A0010             2029884.83
32  Agent A0004             1936405.33
33  Agent A0044             1857368.14
34  Agent A0037             1826723.49
35  Agent A0006             1740447.05
36  Agent A0008             1731242.11
37  Agent A0007             1725146.00
38  Agent A0046             1674860.75
39  Agent A0015             1653234.73
40  Agent A0039             1645970.58
41  Agent A0047             1569245.47
42  Agent A0048             1494192.14
43  Agent A0040             1463236.58
44  Agent A0022             1358776.25
45  Agent A0016             1300200.74
46  Agent A0041             1238818.47
47  Agent A0026             1151801.19
48  Agent A0038             1124498.22
49  Agent A0005             1122696.86

In [191]:
#25
query="""
select a.name, count(l.listing_id) as active_listings from agents a join listings l on a.agent_id = l.agent_id left join sales s on l.listing_id = s.listing_id where s.listing_id is null group by a.name order by active_listings desc limit 3;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\3919691860.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

          name  active_listings
0  Agent A0023              446
1  Agent A0011              439
2  Agent A0008              438

    Buyer & Financing Behavior

In [192]:
#26
query="""
select buyer_type, round(count(*)*100/(select count(*) from buyers), 2) as percentage from buyers group by buyer_type;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\941241596.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

  buyer_type  percentage
0   End User        50.1
1   Investor        49.9

In [193]:
#27
query="""
select l.city,round(sum(case when b.loan_taken =1 then 1 else 0 end)*100.0/count(*),2) as loan_taken_rate from buyers b join sales s on b.sale_id = s.sale_id join listings l on s.listing_id = l.listing_id group by l.city order by loan_taken_rate desc;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\833656353.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

          city  loan_taken_rate
0  Los Angeles            50.99
1      Chicago            50.57
2     New York            50.22
3      Houston            49.71
4      Phoenix            49.50

In [194]:
#28
query="""
select buyer_type, round(avg(loan_amount), 2) as avg_loan_amount from buyers group by buyer_type;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\3949168049.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

  buyer_type  avg_loan_amount
0   End User       2599433.82
1   Investor       2629271.94

In [198]:
#29
query="""
select payment_mode , count(*) as Total_count from buyers group by payment_mode order by Total_count desc limit 1;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\2404063124.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

  payment_mode  Total_count
0         Cash         5088

In [199]:
#30
query="""
select case when b.loan_taken = 1 then 'loan_taken' else 'loan_not_taken' end as loan_status, round(avg(s.days_on_market), 2) as avg_closing_days from buyers b join sales s on b.sale_id = s.sale_id group by loan_status;
"""
result = pd.read_sql(query, conn)
result

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12776\1242066986.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

      loan_status  avg_closing_days
0      loan_taken             62.15
1  loan_not_taken             61.07